"""
Build the car GT-box oracle table: the same trackers, with and without a detector.

The published car table (tools/make_wacv_mot_car_table.py) answers one question
-- how well can this half be tracked today -- and then stops, because every row
consumes the same HiEUM detections and at that detection quality the ordering is
a statement about the detector. This table removes the detector: the same
trackers, the same sequences, the same association code, fed the ground-truth
boxes at score 1.0.

Read as a pair, the two tables separate what the car half measures from what it
appears to measure. The gap between the columns is detection; the spread inside
the oracle columns is association.

Usage:
    python tools/make_wacv_car_oracle_table.py \
        --detector docs/space_tracker/hota_car.csv \
        --oracle   docs/space_tracker/hota_car_oracle.csv \
        --out      wacv-2027-author-kit-template/tables/mot_car_oracle.tex
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

ROWS = [
    ("sort",         "SORT",          r"\citep{bewley2016sort}"),
    ("bytetrack",    "ByteTrack",     r"\citep{zhang2022bytetrack}"),
    ("ocsort",       "OC-SORT",       r"\citep{cao2023ocsort}"),
    ("botsort",      "BoT-SORT",      r"\citep{aharon2022botsort}"),
    ("botsort_reid", "BoT-SORT-ReID", r"\citep{aharon2022botsort}"),
    ("tracktrack",   "TrackTrack",    r"\citep{shim2025tracktrack}"),
    ("masa",         "MASA",          r"\citep{li2024masa}"),
]
METRICS = [("HOTA", r"\textbf{HOTA}", True, 3), ("DetA", "DetA", True, 3),
           ("AssA", "AssA", True, 3), ("IDF1", "IDF1", True, 3),
           ("IDsw", "IDsw", False, 0)]
PLACEHOLDER = r"\tbd"


def read(path: Path) -> dict[str, dict]:
    out = {}
    for r in csv.DictReader(open(path)):
        # the oracle workspace names its trackers "<name>_oracle"
        out[r["tracker"].removesuffix("_oracle")] = r
    return out


def fmt(vals, higher, nd):
    live = [(i, v) for i, v in enumerate(vals) if v is not None]
    cells = [PLACEHOLDER] * len(vals)
    order = sorted(live, key=lambda t: -t[1] if higher else t[1])
    best = order[0][0] if order else None
    second = order[1][0] if len(order) > 1 else None
    for i, v in live:
        s = f"{v:,.0f}" if nd == 0 else f"{v:.{nd}f}"
        s = s.replace("-", "$-$")
        cells[i] = (rf"\textbf{{{s}}}" if i == best
                    else rf"\underline{{{s}}}" if i == second else s)
    return cells


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--detector", required=True)
    ap.add_argument("--oracle", required=True)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    det, orc = read(Path(args.detector)), read(Path(args.oracle))
    n_seq = int(next(iter(det.values()))["n_seqs"])
    cols = {}
    for src, tag in ((det, "d"), (orc, "o")):
        for key, _, higher, nd in METRICS:
            vals = [float(src[k][key]) if k in src else None for k, _, _ in ROWS]
            cols[tag + key] = fmt(vals, higher, nd)
    missing = [n for k, n, _ in ROWS if k not in orc]
    if missing:
        print(f"  no oracle run yet (placeholder): {missing}")
    for k, n, _ in ROWS:
        if k in det and k in orc:
            print(f"  {n:14s} HOTA {float(det[k]['HOTA']):.3f} -> "
                  f"{float(orc[k]['HOTA']):.3f}   AssA "
                  f"{float(det[k]['AssA']):.3f} -> {float(orc[k]['AssA']):.3f}")

    m = len(METRICS)
    L = ["% Generated by tools/make_wacv_car_oracle_table.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering", r"\footnotesize",
         r"\setlength{\tabcolsep}{2.5pt}",
         r"\caption{\textbf{The car part is a detection benchmark, not an "
         r"association benchmark.} The same trackers on the same "
         f"{n_seq} sequences, fed the HiEUM detections of "
         r"\cref{tab:mot_car} (left) and the ground-truth boxes at score $1.0$ "
         r"(right). Association is unchanged between the two; only the boxes "
         r"differ. Every method gains more than $0.6$ HOTA, and the oracle "
         r"columns agree to within $0.03$ AssA: at this scale association is "
         r"very nearly solved, and the ordering of \cref{tab:mot_car} is a "
         r"statement about $\mathrm{mAP}_{50}=0.212$ rather than about the "
         r"trackers. ByteTrack's oracle row should be read as its matching "
         r"without its idea: its mechanism is a two-tier split on detection "
         r"score, and an oracle leaves the low tier empty. \textbf{Bold} is "
         r"best, \underline{underline} second best, within each block; lower is "
         r"better for IDsw.}",
         r"\label{tab:mot_car_oracle}",
         r"\begin{tabular}{@{}l" + "c" * m + " c " + "c" * m + r"@{}}",
         r"\toprule",
         rf"& \multicolumn{{{m}}}{{c}}{{HiEUM detections}} & & "
         rf"\multicolumn{{{m}}}{{c}}{{\textbf{{GT boxes}} (oracle)}} \\",
         rf"\cmidrule(lr){{2-{1 + m}}} \cmidrule(lr){{{3 + m}-{2 + 2 * m}}}",
         r"\textbf{Method} & " + " & ".join(h for _, h, _, _ in METRICS)
         + " & & " + " & ".join(h for _, h, _, _ in METRICS) + r" \\",
         r"\midrule"]
    for i, (k, name, cite) in enumerate(ROWS):
        cells = ([cols["d" + m0][i] for m0, _, _, _ in METRICS] + [""]
                 + [cols["o" + m0][i] for m0, _, _, _ in METRICS])
        L.append(f"{name}{cite} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    args.out.write_text("\n".join(L) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
