"""
Build the car MOT main table for the WACV paper.

Structurally different from the non-car table, in two ways that are results
rather than omissions:

1. **One category.** `car` is a single class, so class-aware and class-agnostic
   scoring coincide and there is no per-category breakdown to give.

2. **Only tracking-by-detection.** The JDT and query-based families cannot be
   trained on this half at all: car ground truth annotates moving objects only,
   so a single-frame detection stage receives contradictory supervision (a
   parked and a moving car are identical pixels, labelled background and
   foreground respectively). That argument is made in the protocol section; here
   it means the table has no JDT or query-based rows, and their absence is
   stated in the caption rather than left as a blank the reader must interpret.

Every row consumes the same HiEUM detections at the same operating point, so
differences are association behaviour. See tools/make_wacv_mot_table.py for the
non-car counterpart.

Usage:
    python tools/make_wacv_mot_car_table.py \
        --hota docs/space_tracker/hota_car.csv \
        --det  /work/anon/experiments/hieum_car_st/pr_curve.json \
        --out  wacv-2027-author-kit-template/tables/mot_car_main.tex
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

ROWS = [
    ("--- Tracking-by-detection (SORT family)", None, None),
    ("sort",         "SORT",          r"\citep{bewley2016sort}"),
    ("bytetrack",    "ByteTrack",     r"\citep{zhang2022bytetrack}"),
    ("ocsort",       "OC-SORT",       r"\citep{cao2023ocsort}"),
    ("botsort",      "BoT-SORT",      r"\citep{aharon2022botsort}"),
    ("botsort_reid", "BoT-SORT-ReID", r"\citep{aharon2022botsort}"),
    ("--- Learned association", None, None),
    ("tracktrack",   "TrackTrack",    r"\citep{shim2025tracktrack}"),
    ("masa",         "MASA",          r"\citep{li2024masa}"),
]
METRICS = [
    ("HOTA", r"\textbf{HOTA}", True,  3),
    ("DetA", "DetA",           True,  3),
    ("AssA", "AssA",           True,  3),
    ("LocA", "LocA",           True,  3),
    ("MOTA", "MOTA",           True,  3),
    ("MOTP", "MOTP",           True,  3),
    ("IDF1", "IDF1",           True,  3),
    ("IDsw", "IDsw",           False, 0),
]
PLACEHOLDER = r"\tbd"


def fmt_column(vals, higher, nd):
    live = [(i, v) for i, v in enumerate(vals) if v is not None]
    cells = [PLACEHOLDER] * len(vals)
    order = sorted(live, key=lambda t: -t[1] if higher else t[1])
    best = order[0][0] if order else None
    second = order[1][0] if len(order) > 1 else None
    for i, v in live:
        s = f"{v:,.0f}" if nd == 0 else f"{v:.{nd}f}"
        # A leading ASCII hyphen is a legal break point, so a negative value in
        # a narrow p{} column splits across two lines ("-" above, digits below).
        # $-$ is a math minus and carries no break opportunity.
        s = s.replace("-", "$-$")
        cells[i] = (rf"\textbf{{{s}}}" if i == best
                    else rf"\underline{{{s}}}" if i == second else s)
    return cells


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--hota", required=True)
    ap.add_argument("--det", required=True, help="HiEUM pr_curve.json, for the caption")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    data = {r["tracker"]: r for r in csv.DictReader(open(args.hota))}
    det = json.loads(Path(args.det).read_text())
    n_seq = int(next(iter(data.values()))["n_seqs"])
    print(f"{len(data)} trackers, {n_seq} sequences, HiEUM mAP50={det['mAP_11pt']}")

    live = [r for r in ROWS if r[1] is not None]
    missing = [n for k, n, _ in live if k not in data]
    if missing:
        print(f"  not yet scored (placeholder): {missing}")

    cols = {}
    for key, _, higher, nd in METRICS:
        vals = [float(data[k][key]) if k in data else None for k, _, _ in live]
        cols[key] = fmt_column(vals, higher, nd)
    for k, n, _ in live:
        if k in data:
            print(f"  {n:14s} HOTA={float(data[k]['HOTA']):.4f} "
                  f"DetA={float(data[k]['DetA']):.4f} AssA={float(data[k]['AssA']):.4f}")

    L = []
    L.append("% Generated by tools/make_wacv_mot_car_table.py -- do not edit by hand.")
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(
        r"\caption{Multi-object tracking on the \textbf{car} half of the "
        f"Space-Tracker-MOT test split ({n_seq} sequences). "
        r"Every row consumes the same HiEUM detections "
        rf"($\mathrm{{mAP}}_{{50}}={det['mAP_11pt']:.3f}$, \cref{{tab:mot_detection}}) "
        r"at the same operating point, so the spread is association behaviour. "
        r"\emph{car} is a single class, so class-aware and class-agnostic "
        r"scoring coincide. The table contains no JDT or query-based rows "
        r"because those families cannot be trained on this half at all: car "
        r"ground truth annotates moving objects only, and a single-frame "
        r"detection stage is therefore given a parked and a moving vehicle as "
        r"identical pixels labelled background and foreground respectively "
        r"(\cref{sec:exp_protocol}). \textbf{MOTA is negative for every method}, "
        r"which is a property of that same protocol rather than a failure of the "
        r"trackers: unannotated stationary vehicles are counted as false "
        r"positives, so a detector that finds every car on the ground is "
        r"penalised for the ones the ground truth omits. HOTA and its DetA / "
        r"AssA decomposition are the informative columns here. Metrics follow "
        r"\cref{sec:eval_metrics} at $\mathrm{IoU}\geq0.5$. \textbf{Bold} is "
        r"best, \underline{underline} second best; lower is better for IDsw "
        r"only.}")
    L.append(r"\label{tab:mot_car}")
    L.append(r"\setlength{\tabcolsep}{3.5pt}")
    L.append(r"\renewcommand{\arraystretch}{1.12}")
    L.append(r"\resizebox{\columnwidth}{!}{%")
    L.append(r"\begin{tabular}{l *{7}{>{\centering\arraybackslash}p{3.0em}} r}")
    L.append(r"\toprule")
    L.append(r"\textbf{Method} & " + " & ".join(h for _, h, _, _ in METRICS) + r" \\")
    L.append(r"\midrule")
    ncol = 1 + len(METRICS)
    i = 0
    for entry in ROWS:
        if entry[1] is None:
            if i:
                L.append(r"\midrule")
            L.append(rf"\multicolumn{{{ncol}}}{{l}}{{\emph{{{entry[0][4:]}}}}} \\")
            continue
        _, name, cite = entry
        L.append(f"{name}{cite} & "
                 + " & ".join(cols[k][i] for k, _, _, _ in METRICS) + r" \\")
        i += 1
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"}")
    L.append(r"\end{table}")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
