#!/usr/bin/env python
"""Emit ``tables/sot_composition.tex``: what Space-Tracker-SOT is made of.

The section used to open with a paragraph of twenty-odd numbers, which is the
worst way to deliver a composition: the reader cannot compare two sources
without re-reading the sentence, and every number has to be re-typed by hand
whenever the release changes.  This generates the same facts as a table, read
directly out of the released annotation, so the two can never disagree.

Two blocks over the same columns --- by source dataset, then by target class ---
because those are the two partitions of the same 395 sequences that a reader
actually wants to cut by.

Usage
-----
    python tools/make_wacv_sot_composition_table.py
"""

from __future__ import annotations

import argparse
import collections
import json
import os
from pathlib import Path

import numpy as np

RELEASE = Path(os.environ.get("SPACE_TRACKER_RELEASE",
                              "/data/anon/release/space_tracker"))

#: Sub-8-px is the tiny regime the benchmark is built around; see the pipeline
#: section. Counted per sequence on its median target, not per box.
TINY_PX = 8.0

#: Printed names. ``car-large`` is SV248S's large-road-vehicle class, which we
#: keep separate from ``car`` rather than folding in.
CAT_ORDER = ["car", "car-large", "ship", "airplane", "train"]
SRC_NAME = {"ootb": "OOTB", "satsot": "SatSOT", "sv248s": "SV248S"}


def num(x: int) -> str:
    return f"{x:,}".replace(",", "{,}")


def row(label: str, vs: list[dict]) -> str:
    n_frames = np.array([v["n_frames"] for v in vs])
    vis = sum(v["n_visible_frames"] for v in vs)
    s = np.array([v["median_sqrt_area_px"] for v in vs], dtype=float)
    res = len({(v["width"], v["height"]) for v in vs})
    return (f"{label} & {len(vs)} & {num(int(n_frames.sum()))} & {num(vis)} & "
            f"{res} & {num(int(np.median(n_frames)))} & {np.median(s):.1f} & "
            f"{int((s < TINY_PX).sum())} \\\\")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path,
                    default=Path("wacv-2027-author-kit-template/tables/"
                                 "sot_composition.tex"))
    args = ap.parse_args()

    data = json.loads((RELEASE / "sot" / "annotations"
                       / "space_tracker_sot.json").read_text())
    vids = data["videos"]

    by_src = collections.defaultdict(list)
    by_cat = collections.defaultdict(list)
    for v in vids:
        by_src[v["source_dataset"]].append(v)
        by_cat[v["category"]].append(v)

    # Which sources hold each class -- the one fact the two blocks cannot show
    # on their own, and the reason car-large and train are structurally awkward.
    only = {c: sorted({v["source_dataset"] for v in vs})
            for c, vs in by_cat.items()}
    single = [f"\\emph{{{c}}} ({SRC_NAME[only[c][0]]} only)"
              for c in CAT_ORDER if len(only[c]) == 1]
    n_tiny = sum(v["median_sqrt_area_px"] < TINY_PX for v in vids)

    lines = [
        "% Generated by tools/make_wacv_sot_composition_table.py "
        "-- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{2.9pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\caption{Composition of Space-Tracker-SOT, by source dataset and by "
        "target class; the two blocks partition the same 395 sequences. "
        "\\emph{Vis.} counts the frames in which the target is actually "
        "visible, the remainder being fully occluded or out of view. "
        "\\emph{\\#Res} is the number of distinct frame sizes, which is close "
        "to the number of sequences because the sources release each target as "
        "an independently cropped patch rather than as a full scene. "
        "\\emph{Len} is the median sequence length in frames and $\\tilde s$ "
        "the median over sequences of the sequence's own median "
        "$s=\\sqrt{\\mathrm{area}}$, in px. \\emph{Tiny} counts sequences with "
        f"$\\tilde s<{TINY_PX:.0f}$\\,px; {n_tiny} of the {len(vids)} sequences "
        "fall inside that regime. Every class is drawn from at least two "
        "sources except " + " and ".join(single) + ". \\emph{car-large} is "
        "SV248S's large-road-vehicle class, which we keep separate from "
        "\\emph{car} rather than folding it in, since its median target is "
        "roughly twice the size.}",
        "\\label{tab:sot_composition}",
        "\\begin{tabular}{@{}l rrrrr rr@{}}",
        "\\toprule",
        " & \\#Seq & \\#Frames & Vis. & \\#Res & Len & $\\tilde s$ & Tiny \\\\",
        "\\midrule",
        "\\multicolumn{8}{@{}l}{\\emph{By source dataset}} \\\\",
    ]
    for src in sorted(by_src, key=lambda s: -len(by_src[s])):
        lines.append(row(SRC_NAME[src], by_src[src]))
    lines += ["\\midrule",
              "\\multicolumn{8}{@{}l}{\\emph{By target class}} \\\\"]
    for cat in CAT_ORDER:
        lines.append(row(f"\\emph{{{cat}}}", by_cat[cat]))
    lines += ["\\midrule",
              row("\\textbf{Space-Tracker-SOT}", vids),
              "\\bottomrule",
              "\\end{tabular}",
              "\\end{table}"]

    args.out.write_text("\n".join(lines) + "\n")
    print(f"written: {args.out}")
    print("\n".join(lines[-12:]))


if __name__ == "__main__":
    main()
