"""
Build the supplementary OOTB geometry table for the WACV paper.

The headline table collapses OOTB's oriented ground truth and every prediction
to horizontal (axis-aligned) boxes, so all methods solve one localisation task. That choice
hides something real: only the mask-producing trackers can actually emit an
oriented box, and OOTB is the one part of Space-Tracker where orientation is
annotated. This table recovers that analysis without letting it contaminate the
headline number.

Each tracker is scored on the 74 released OOTB sequences twice:

* **HBB** — GT polygon and prediction both reduced to their enclosing horizontal
  (axis-aligned) box. HBB and AABB are the same object; we say HBB throughout to
  match the remote-sensing HBB/OBB convention and the `Output` column, which
  states which geometry a tracker is *able* to produce.
* **OBB** — polygon IoU against the oriented GT. A mask tracker supplies a
  genuine oriented quadrilateral here; an HBB tracker can only supply the four
  corners of its upright box, so it pays for every degree of target rotation.

The gap between the two columns therefore measures something different for the
two families, and the table is meant to be read family-wise, not as a ranking.

Usage:
    python tools/make_wacv_obb_table.py \
        --runs   /path/to/SOT_whole_dataset_<date> \
        --release /path/to/release/space_tracker \
        --out    wacv-2027-author-kit-template/tables/sot_obb_supp_table.tex
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lightning_modules.sot_metrics import _compute_from_sequences
from tools.aggregate_sot_release import records_by_sequence
from tools.make_wacv_sot_table import released_sequences, find_run, fmt_col

# key, display name, output geometry the tracker can actually produce
TRACKERS = [
    ("siamrpn",    "SiamRPN++",   "HBB"),
    ("siamfc",     "SiamFC",      "HBB"),
    ("ostrack",    "OSTrack-384", "HBB"),
    ("odtrack",    "ODTrack",     "HBB"),
    ("lorat",      "LoRAT-g378",  "HBB"),
    ("smalltrack", "SmallTrack",  "HBB"),
    ("sam2",       "SAM 2",       r"mask $\rightarrow$ OBB"),
    ("samurai",    "SAMURAI",     r"mask $\rightarrow$ OBB"),
    ("sam3",       "SAM 3",       r"mask $\rightarrow$ OBB"),
]


def score(runs_root: Path, tracker: str, keep: set[str], aabb: bool) -> dict:
    pim = find_run(runs_root, tracker, "ootb")
    if pim is None:
        raise FileNotFoundError(f"no OOTB run for {tracker}")
    seqs, _ = records_by_sequence(pim, keep, rescore_aabb=aabb)
    return _compute_from_sequences(list(seqs.values()))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs", required=True)
    ap.add_argument("--release", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    keep = set(released_sequences(Path(args.release))["ootb"])
    print(f"OOTB released sequences: {len(keep)}")

    rows = []
    for key, name, geom in TRACKERS:
        a = score(Path(args.runs), key, keep, aabb=True)
        p = score(Path(args.runs), key, keep, aabb=False)
        rows.append((name, geom, a, p))
        print(f"  {name:12s} {geom:22s} AABB SR={a['success_auc']:.4f}  "
              f"OBB SR={p['success_auc']:.4f}  delta={p['success_auc']-a['success_auc']:+.4f}")

    # NPR and P@5 are centre-distance metrics, and an HBB is the enclosing box
    # of its OBB, so the two share a centre and these columns are identical to
    # three decimals under both protocols (verified below). Reporting them twice
    # would pad the table with four columns that carry no information, so they
    # are given once, from the AABB pass.
    for r in rows:
        for key in ("norm_precision_auc", "precision_5"):
            if abs(r[2][key] - r[3][key]) > 5e-3:
                raise RuntimeError(
                    f"{r[0]}: {key} differs between protocols "
                    f"({r[2][key]:.4f} vs {r[3][key]:.4f}) -- it is no longer safe "
                    "to report this column once; restore the paired columns.")

    cols = {
        "a_sr":  fmt_col([r[2]["success_auc"] for r in rows]),
        "p_sr":  fmt_col([r[3]["success_auc"] for r in rows]),
        "npr":   fmt_col([r[2]["norm_precision_auc"] for r in rows]),
        "p5":    fmt_col([r[2]["precision_5"] for r in rows]),
    }
    deltas = [r[3]["success_auc"] - r[2]["success_auc"] for r in rows]

    L = []
    L.append("% Generated by tools/make_wacv_obb_table.py -- do not edit by hand.")
    L.append("% Requires: \\usepackage{booktabs, multirow, array}")
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(
        r"\caption{Oriented-box analysis on the "
        f"{len(keep)}"
        r" released OOTB sequences, the only part of Space-Tracker whose ground truth "
        r"carries orientation. \textbf{HBB} reduces the oriented GT and every prediction "
        r"to its enclosing horizontal (axis-aligned) box; this is the protocol used in the "
        r"main results, and it is what the OOTB v1.0 toolkit does for upright trackers. "
        r"\textbf{OBB} scores "
        r"polygon IoU against the oriented GT. Only the mask-producing trackers can emit a "
        r"genuinely oriented quadrilateral; an upright tracker can offer no more than the four "
        r"corners of its own box, so $\Delta$SR conflates tracking quality with the "
        r"representational limit of the output. The two families must therefore be read "
        r"separately, and this is precisely why the main table scores everything "
        r"with horizontal boxes. \textbf{Bold} is best, \underline{underline} second best "
        r"within a column. NPR and P@5 are centre-distance metrics and an HBB shares its "
        r"OBB's centre, so they are identical under both protocols and reported "
        r"once -- the geometry choice moves overlap, not localisation.}"
    )
    L.append(r"\label{tab:sot_obb_supp}")
    L.append(r"\setlength{\tabcolsep}{4pt}")
    L.append(r"\renewcommand{\arraystretch}{1.15}")
    L.append(r"\resizebox{\columnwidth}{!}{%")
    L.append(r"\begin{tabular}{l l *{5}{>{\centering\arraybackslash}p{3.0em}}}")
    L.append(r"\toprule")
    L.append(r"\multirow{2}{*}{\textbf{Method}} & \multirow{2}{*}{\textbf{Output}}")
    L.append(r" & \multicolumn{3}{c}{\textbf{SR}}")
    L.append(r" & \multicolumn{2}{c}{\textbf{Centre-based}} \\")
    L.append(r"\cmidrule(lr){3-5} \cmidrule(lr){6-7}")
    L.append(r" & & HBB & OBB & $\Delta$ & NPR & P@5 \\")
    L.append(r"\midrule")
    for i, (name, geom, _, _) in enumerate(rows):
        if i == 6:
            L.append(r"\midrule")
        L.append(
            f"{name} & {geom} & "
            f"{cols['a_sr'][i]} & {cols['p_sr'][i]} & {deltas[i]:+.3f} & "
            f"{cols['npr'][i]} & {cols['p5'][i]} \\\\"
        )
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"}")
    L.append(r"\end{table}")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
