#!/usr/bin/env python
"""Emit ``tables/mot_composition.tex``: what Space-Tracker-MOT is made of.

The MOT counterpart of ``tools/make_wacv_sot_composition_table.py``, and the
same argument for existing: the section used to open with a paragraph of twenty
numbers that no reader can compare across without re-reading the sentence.

Two blocks over one set of columns, as in the SOT table, but the second one
behaves differently and the caption has to say so.  On the SOT side a sequence
has exactly one designated target, so the class block is a partition.  Here a
sequence carries every instance of every class it contains, and 69 of them carry
more than one, so a sequence is counted once per class it holds and the class
block sums above the total.

The unit of the size statistics is also different.  A SOT sequence has one
target and one size; an MOT sequence has hundreds, so scale is summarised over
tracks rather than over sequences.

Usage
-----
    python tools/make_wacv_mot_composition_table.py
"""

from __future__ import annotations

import argparse
import collections
import json
import os
from pathlib import Path

import numpy as np

RELEASE = Path(os.environ.get("SPACE_TRACKER_RELEASE",
                              "/data/anon/release/space_tracker"))

#: Same tiny boundary as everywhere else in the paper, but counted per track.
TINY_PX = 8.0

CAT_ORDER = ["car", "ship", "airplane", "train"]
SRC_NAME = {"satmtb": "SAT-MTB", "sdmcar": "SDM-Car",
            "rscardata": "RsCarData", "viso": "VISO"}


def num(x: int) -> str:
    return f"{x:,}".replace(",", "{,}")


def row(label: str, vids: list[dict], tracks: list[dict]) -> str:
    n_frames = np.array([v["n_frames"] for v in vids])
    s = np.array([t["median_sqrt_area_px"] for t in tracks], dtype=float)
    n_boxes = sum(t["n_boxes"] for t in tracks)
    return (f"{label} & {len(vids)} & {num(int(n_frames.sum()))} & "
            f"{num(len(tracks))} & {num(n_boxes)} & {np.median(s):.1f} & "
            f"{num(int((s < TINY_PX).sum()))} \\\\")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path,
                    default=Path("wacv-2027-author-kit-template/tables/"
                                 "mot_composition.tex"))
    args = ap.parse_args()

    data = json.loads((RELEASE / "mot" / "annotations"
                       / "space_tracker_mot.json").read_text())
    vids = data["videos"]
    by_id = {v["id"]: v for v in vids}
    cats = {c["id"]: c["name"] for c in data["categories"]}

    tracks_of_video = collections.defaultdict(list)
    for t in data["tracks"]:
        tracks_of_video[t["video_id"]].append(t)

    by_src = collections.defaultdict(list)
    for v in vids:
        by_src[v["source_dataset"]].append(v)

    by_cat = collections.defaultdict(list)
    for t in data["tracks"]:
        by_cat[cats[t["category_id"]]].append(t)

    multi = sum(1 for v in vids if len(v.get("categories_in_sequence", [])) > 1)
    sizes = collections.Counter((v["width"], v["height"]) for v in vids)
    (w1, h1), n1 = sizes.most_common(1)[0]
    (w2, h2), n2 = sizes.most_common(2)[1]
    lens = np.array([v["n_frames"] for v in vids])
    lo, hi, med = int(lens.min()), int(lens.max()), int(np.median(lens))

    lines = [
        "% Generated by tools/make_wacv_mot_composition_table.py "
        "-- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{2.2pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\caption{Composition of Space-Tracker-MOT, by source dataset and by "
        f"object class. The source block partitions the {len(vids)} sequences; "
        "the class block does \\emph{not}, because a sequence carries every "
        f"instance of every class it contains and {multi} of them contain more "
        "than one, so a sequence and its frames are counted once per class "
        "present and the block sums above the total. Sequences run from "
        f"{lo} to {hi} frames with a median of {med}. "
        "Scale is summarised over \\emph{tracks} "
        "rather than sequences, an MOT sequence having no single designated "
        "target: $\\tilde s$ is the median over tracks of the track's own median "
        f"$s=\\sqrt{{\\mathrm{{area}}}}$, in px, and \\emph{{Tiny}} counts tracks "
        f"with $\\tilde s<{TINY_PX:.0f}$\\,px. Frame sizes are less varied than in "
        f"the SOT part---{len(sizes)} distinct sizes over {len(vids)} sequences, "
        f"dominated by ${w1}\\times{h1}$ ({n1} sequences) and ${w2}\\times{h2}$ "
        f"({n2})---because these sources release whole scenes rather than "
        "per-target crops.}",
        "\\label{tab:mot_composition}",
        "\\begin{tabular}{@{}l rrrr rr@{}}",
        "\\toprule",
        " & \\#Seq & \\#Frames & \\#Tracks & \\#Boxes & $\\tilde s$ & Tiny \\\\",
        "\\midrule",
        "\\multicolumn{7}{@{}l}{\\emph{By source dataset}} \\\\",
    ]
    for src in sorted(by_src, key=lambda s: -len(by_src[s])):
        vs = by_src[src]
        lines.append(row(SRC_NAME[src], vs,
                         [t for v in vs for t in tracks_of_video[v["id"]]]))

    lines += ["\\midrule",
              "\\multicolumn{7}{@{}l}{\\emph{By object class "
              "(sequences may appear twice)}} \\\\"]
    for cat in CAT_ORDER:
        trs = by_cat[cat]
        seq_ids = {t["video_id"] for t in trs}
        lines.append(row(f"\\emph{{{cat}}}", [by_id[i] for i in seq_ids], trs))

    lines += ["\\midrule",
              row("\\textbf{Space-Tracker-MOT}", vids, data["tracks"]),
              "\\bottomrule",
              "\\end{tabular}",
              "\\end{table}"]

    args.out.write_text("\n".join(lines) + "\n")
    print(f"written: {args.out}")
    print("\n".join(lines[-13:]))


if __name__ == "__main__":
    main()
